### ISSUE TITLE
Repository not found.

### ISSUE THREAD

**Issue by td-heinm** [AdobeDocs/commerce-pwa-studio#154]
Issue in /src/pages/metapackages/venia-sample-data/index.md

<img width="555" alt="image" src="https://user-images.githubusercontent.com/102971295/192341327-4e93380c-c72c-4f4c-ab3c-d7a4d4f024eb.png">

**Comment by jeff-matthews** [comment]
Also reported in #190 

@dshevtsov, you recently installed Venia sample data. Which repo did you use?

**Comment by dshevtsov** [comment]
> @dshevtsov, you recently installed Venia sample data. Which repo did you use?

@jeff-matthews, I didn't use GitHub repos. I used Composer installation like in https://developer.adobe.com/commerce/pwa-studio/guides/packages/venia/sample-data/
