### ISSUE TITLE
Graphql url returns error

### ISSUE THREAD

**Issue by sreerajsaseendran** [AdobeDocs/commerce-pwa-studio#169]
Getting error while setting up pwa studio. I believe this is because the graphql url returns some error.
https://venia-develop-**********************magentosite.cloud/graphql/ returns below error.
"An error has happened during application run. See exception log for details.
Could not write error message to log. Please use developer mode to see the message."

Because of the above issue yarn watch throws invalid json error.

Please help how to resolve this

**Comment by jeff-matthews** [comment]
Doesn't appear to be related to docs. Please raise in the https://github.com/magento/pwa-studio repo.
