### ISSUE TITLE
Metapackage End of Life Messaging

### ISSUE THREAD

**Issue by nrdevau** [AdobeDocs/commerce-pwa-studio#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

While making some changes to the Metapackage instructions I was informed that as of M2.4.7-beta, the meta package code (GraphQLPwa and GraphQlAux) modules are going to be bundled into the core Magento repository.

If this is definitely happening, it would be good to have an info box at the head of each of the metapackage pages that alerts those reading it, so that they can prepare.

Other places to consider some messaging:
- The page navigation could say `Metapackage (Deprecated)`
- Possibly as part of the yarn/npm buildpack output - although this would be unnecessary once M2.4.7 is ready I believe

If that is the case we just need to determine the right copy for the message and do it. I'm more than happy to donate my time to do that once we've landed on the correct wording.

cc @keharper (originally informed me on this)

An example could be using the BlockQuote function in MD:

Like so
<<< END_OF_EXAMPLE

---
> **&#9432;** This metapackage is currently separately required in each Magento backend the PWA is configured for, but will be bundled into the Core Magento codebase as of Magento 2.4.7
---
END_OF_EXAMPLE

**Comment by jeff-matthews** [comment]
Thanks @nrdevau, but I don't think we need this in the docs backlog. If EOL becomes a thing, we'll revisit then.

**Comment by nrdevau** [comment]
Oh, so it isn't a confirmed EOL decision? For the foreseeable future we should work with this Metapackage in our M2 backends?

Thanks for confirming @jeff-matthews!

**Comment by jeff-matthews** [comment]
@nrdevau 

Yes, not confirmed as far as I know. That information would have to come from an official Adobe source first before the docs get updated.
